project/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include(debug_toolbar.urls)),
    path('', include('youtube.urls',namespace='content')),
   
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

youtube/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from .views import HomeView,NewVideo,CommentView,LoginView,SignUpView,LogoutView,VideoView
app_name= 'youtube'
urlpatterns = [
    path('', HomeView.as_view(),name='home'),
    path('new_video/',NewVideo.as_view(),name='newVid'),
    path('login/',LoginView.as_view(),name='login'),
    path('logout/',LogoutView.as_view(),name='logout'),
    path('register/',SignUpView.as_view(),name='register'),  
    path('comment',CommentView.as_view(),name='comment'),
    path('video/<int:id>',VideoView.as_view(),name='video'), 
 
]

templates/base_generic.html
<!DOCTYPE html>
<html>

<head>

    <title>{% block title %} {% endblock title %} - Youtube Clone Web </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

</head>





<body>
    <center>
        <ul class="nav nav-tabs">
            <li class="nav-item">
                <a class="nav-link 
                {% if request.path == '/' %}
                    active
                {% endif %}
                    " aria-current="page" href="{% url 'content:home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {% if request.path == '/new_video/' %}
                active
            {% endif %}" href="{% url 'content:newVid' %}">Add Video</a>
            </li>
            <li class="nav-item">
                {% if tabName == "login" %}
                <a class="nav-link {% if request.path == '/login/' %}
                active
            {% endif %}" href="{% url 'content:login' %}">SignIn</a>
                <li class="nav-item">
                    <a class="nav-link 
                {% if request.path == '/register/' %}
                active
                {% endif %}" href="{% url 'content:register' %}">SignUp</a>
                </li>
                {% elif tabName == "logout" %}
                <a class="nav-link 
                {% if request.path == '/logout' %}
                active
                {% endif %}" href="{% url 'content:logout' %}">SignOut</a> {% endif %}
            </li>

            <li class="nav-item">
                <a class="nav-link {% if request.path == '/support/' %}
                active
            {% endif %}" href="#" tabindex="-1" aria-disabled="true">Support</a><br>
            </li>
        </ul>
        {% block body %} {% endblock body%}

    </center>
</body>






</html>

templates/form_generic.html
{% extends "base_generic.html" %} {% block title %} {{title}} {% endblock title %} {% block body %}
<form method='POST' enctype='multipart/form-data'>
    {% csrf_token %}
    <table>
        {{form}}
        <br> {% for text_1 in body_text %} {{text_1}}
        <br> {% endfor %}
        <tr>
            <td>{{hint_text}}</td>

        </tr>

        <tr>


            <td> <button type="submit" class="btn btn-primary">{{btnName}}</button></td>
        </tr>

    </table>
</form>
{% endblock body %}